gadicc/node-yahoo-finance2

.circleci/config.yml, package.json
This PR fixes the indent of the `codecov/upload` part of the CI. It also adds typechecking to the CI. The CI will automatically run `tsc --noEmit` to check for any type errors.
=> ci: fix codecov and add ts type checking to ci

schema.json, src/modules/search.spec.ts, src/modules/search.ts, tests/http/search-BABA.json, tests/http/search-Bayerische Motoren Werke AG.json, tests/http/search-Evolution Gaming Group.json, tests/http/search-OCDO.L.json
This PR fixes an issue where Yahoo doesn't always return `SearchQuoteYahooEquity.longname`.
See https://github.com/gadicc/node-yahoo-finance2/issues/13.
Change so that `SearchQuoteYahooEquity.longname` is an optional property which is not always returned by Yahoo. I've also added some more tests to the search module.
- change `longname` to be an optional property
- add more tests to `search.spec.ts`
- `schema.json` changed after running `yarn generateSchema`
```
$ jest --verbose --silent --t search
PASS  src/modules/search.spec.ts
search
✓ passed validation for search: AAPL (75 ms)
✓ passed validation for search: OCDO.L (2 ms)
✓ passed validation for search: BABA (1 ms)
✓ passed validation for search: Evolution Gaming Group (1 ms)
✓ passed validation for search: Bayerische Motoren Werke …
```
=> fix(search): change longname to be an optional property

docs/validation.md
This PR fixes some typos in the validation docs.
`Fails` -> `Failures`
`import` -> `important`
The link fragments were not updated, mainly for the purpose of not breaking bookmarks and other links.
=> chore(docs): fix typos in validation docs

src/lib/moduleExec.ts, src/modules/quote.ts
This PR fixes https://github.com/gadicc/node-yahoo-finance2/issues/24
- `moduleExec`: Change so that we always pass an object to `validateAndCoerceTypes`
- `quote`: no need to default to empty object for overrides since that is done later
=> fix(moduleExec): pass correct object to validation

README.md, docs/README.md, docs/modules/recommendationsBySymbol.md, schema.json, src/index-common.ts, src/modules/recommendationsBySymbol.spec.ts, src/modules/recommendationsBySymbol.ts, tests/http/recommendationsBySymbol-0P000071W8.TO.json, tests/http/recommendationsBySymbol-AAPL-BMW.DE.json, tests/http/recommendationsBySymbol-AAPL.json, tests/http/recommendationsBySymbol-BABA.json, tests/http/recommendationsBySymbol-OCDO.L.json, tests/http/recommendationsBySymbol-QQQ.json
This PR adds a new module `recommendationsBySymbol` that retrieves "Similar instruments" to the one's you pass.
When you view a specific symbol on Yahoo Finance they will show a widget on the right hand side; **"People also watch"** - which the user might be interested in. Below you can see what is shown when browsing [Activision Blizzard ($ATVI)](https://finance.yahoo.com/quote/ATVI).
`https://query2.finance.yahoo.com/v6/finance/recommendationsbysymbol/${symbols}`
- Accepts multiple symbols, comma separated
- No other query parameters as far as I know
The response back from Yahoo looks like this:
```
{
"finance": {
"result": [
{
"symbol": "AAPL",
"recommendedSymbols": [
{ "symbol": "AMZN", "score": 0.292276 },
{ "symbol": "FB", "score": 0.274045 },
{ "symbol": "GOOG", "score": 0.272778 …
```
=> feat: new module recommendationsBySymbol

schema.json, src/modules/quote.ts
This PR fixes https://github.com/gadicc/node-yahoo-finance2/issues/32
- Extend `QuoteBase. marketState` to also accept `"POST"` and `"POSTPOST"`
- Update `schema.json` by running `yarn generateSchema`
=> fix(quote): extend marketState property

.prettierrc.yaml
This PR changes so that Prettier respects `.editorconfig`.
Before Visual Studio Code didn't pick up the settings defined in `.editorconfig`, see GIF below.
- add `editorconfig: true` to `.prettierrc.yaml`
Personally I tend to only use Prettier, but this seems to be the way to do it when using `.editorconfig` as well.
=> chore: prettier to respect editorconfig

src/modules/quote.ts
This PR fixes the type specificity for the function overloading for the quote module, so that we get the correct typed response by default.
I noticed that when using the `quote` module I didn't get back the expected `Quote` type, see below.
```
const what = await yahooFinance2.quote('AAPL'); // <-- this was any
```
- change specificity for quote module
=> chore: change specificity for quote module

src/modules/quote.spec.ts, src/modules/recommendationsBySymbol.spec.ts
Ref #51
This PR switches from using the JS inbuilt `forEach` function to using the `jest` inbuilt `it.each` function for testing a test against multiple symbols.
- Switch from `testSymbols.forEach()` to `it.each(testSymbols)()`
- Add better names for tests using `forEach`
=> chore(tests): switch from using forEach to using it.each

docs/README.md
Ref #50
This PR adds a note about the `devel` option being used in the browser.
=> chore(docs): add note about devel option in browser

schema.json, src/modules/quote.ts, tests/http/quote-BEKE-10am.json, tests/http/quote-BEKE.json, tests/http/quote-BFLY-10am.json, tests/http/quote-BFLY.json, tests/symbols.ts
Fixes #61 
* Add those property with optional to [quote.ts](https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/quote.ts#L96).
```javascript
trailingThreeMonthReturns?: number; // 16.98
trailingThreeMonthNavReturns?: number; // 17.08
ipoExpectedDate?: Date; // "2020-08-13",     <---- added
newListingDate?: Date; // "2021-02-16",      <---- added
```
* Add queto-BEKE.json 
* Add queto-BFLY.json
=> fix(quote): add additional properties (#61)

src/modules/quoteSummary.spec.ts
This PR does the (hopefully) final switch from using `forEach` to `it.each`.
- `quoteSummary` tests now use `it.each(symbols)()` instead of `forEach`
=> chore(tests): more switching from forEach to it.each

src/lib/validateAndCoerceTypes.ts
Ref #50 
This PR loads `process` only when defined during validation error logging.
- `process` is only loaded when defined, using the nice old `typeof` trick. This prevents errors in a browser environment.
=> fix(validation): load process only when defined during validation logging (#50)

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/meta.md, .github/ISSUE_TEMPLATE/new-module.md, .github/ISSUE_TEMPLATE/validation.md, .github/pull_reequest_template.md
Closes #116.
- Add issue templates
- Add `config.yml`
- Add PR template
@gadicc I didn't add multiple PR templates, they aren't quite easy to use, apparently.
=> chore(gh-templates): add pr and issue templates [skip ci]

README.md, docs/README.md, docs/other/setGlobalConfig.md, package.json, schema.json, src/lib/options.ts, src/lib/setGlobalConfig.spec.ts, src/lib/setGlobalConfig.ts, src/lib/yahooFinanceFetch.ts, src/typings/interfaces.ts
Relating to #129.
- Add `setGlobalConfig` function
- Add tests for `setGlobalConfig`
- Add docs
- Refactor `Options` interface into a new `interfaces.ts` file
- Change schema script to generate schema defs for refactored out interface
@gadicc Is the name good? Also, all tests seem to pass, yet some unnecessary things have been added to the schema. I am not sure whether it is worth it.
Also, should this function merge config several levels deep, or not?
=> feat(setGlobalConfig): add setGlobalConfig function

README.md, docs/README.md
- fix broken documentation links for the `setGlobalConfig` documentation
This PR fixes two links which reffered to the wrong url
=> docs: fix broken doc links

docs/concurrency.md, docs/validation.md
Ref #129.
- Update docs to use `setGlobalConfig` instead of `_opts` directly
=> docs: update to use setGlobalConfig

schema.json, src/modules/options.ts
Closes #175.
- Accept `date` option in `options` module
=> feat: accept `date` option in `options` module

docs/modules/quote.md, schema.json, src/modules/quote.spec.ts, src/modules/quote.ts
Relates to #150.
- Allows a `{ return: "type" }` query option to force return type of `array`, `object` or `map`
**Other New Feature**
=> feat(quote): support { "return": "array"* | "map" | "object" } param

docs/modules/quoteSummary.md
Closes #260 .
- improve the `quoteSummary.md` documentation
Only the `secFilings` submodule is missing documentation. However this is currently not possible since it looks like yahoo changed the API and now the submodule always throws a validation error. The progress of this issue can be tracked here #261
=> Improve quoteSummary documentation

docs/modules/options.md
The old docs didn't mention that you could specify an expiration date. I
added in a simple example about how to do this and the number type of
the expiration date in the table.
See #287.
See the docs in the diff
I think we might consider having support for both number and date objects -- I haven't done too much Typescript so idk how much of a bad practice this is
=> Update options.md to explain expiration date

schema.json, src/modules/search.ts
This PR fixes an issue for the `search` method where validation was failing due to two new properties being added two the response from Yahoo Finance. Closes https://github.com/gadicc/node-yahoo-finance2/issues/398.
- Add two new properties `culturalAssets` and `timeTakenForCulturalAssets`
Since I don't know the data that can be returned for `culturalAssets` it's currently set to `Array<any>`, just in order for the validation to pass. Created a new issue where we can track and improve this; https://github.com/gadicc/node-yahoo-finance2/issues/399
=> fix: update SearchResult to include new properties

docs/validation.md, schema.json, src/index-common.ts, src/lib/validateAndCoerceTypes.ts, src/modules/chart.ts, src/modules/historical.ts, src/modules/insights.ts, src/modules/options.ts, src/modules/quote.ts, src/modules/quoteSummary-iface.ts, src/modules/recommendationsBySymbol.ts, src/modules/search.ts, src/modules/trendingSymbols.ts
Closes #401.
Not done yet but in process.
We need to make a distinction between Options and Results, since we do actually rely on `{ additionalProperties: false }` to validate the options the user is passing to various modules (and ensure e.g. they didn't mispell anything).
Should be fine to simply traverse the tree and apply `additionalProperties` on interfaces with names ending `Options` (while remembering there's a module called `Options` too, and see if there are any other naming conflicts).
=> feat(validation): allow additionalProperties (closes #401)

docs/README.md, docs/modules/autoc.md, docs/modules/chart.md, docs/modules/historical.md, docs/modules/insights.md, docs/modules/options.md, docs/modules/quote.md, docs/modules/quoteSummary.md, docs/modules/recommendationsBySymbol.md, docs/modules/search.md, docs/modules/trendingSymbols.md, docs/other/quoteCombine.md
Closes #425.
- Added link from every module type definition to its documentation page.
- Small typos on docs
=> (docs) Link from every module doc to the type defs

CONTRIBUTING.md, src/modules/historical.ts
Closes #457  .
- Fixes #457
- Fixes small typo in CONTRIBUTING.md
First time submitting a 'real' pull request with code. I didn't add tests because I'm not familiar with it.
Also, I'm not 100% sure if my change is the best decision for this issue, but I try a few different options and I liked this the most. Please let me know if I can improve this further and if I made something wrong so I can improve next time. Thanks for the amazing project, as always! :)
=> [historical] throw error if given a string for period{1,2} that is invalid input for new Date()

schema.json, src/modules/insights.ts, src/modules/quoteSummary-iface.ts
Partially Closes #663 , and closes #664.
- stopLoss under insights is not always present in response, changed to optional
- sectorInfo under insights is not always present in response, changed to optional
- Added missing Filing forms for some non-US companies
=> Fixes Insights and SEC Filings Validation Errors

README.md, bin/yahoo-finance.js
Minor changes to make it easier to use the CLI.
- Add a help command to CLI (`--help` or `-h`
- Add a few more examples to the README file
Might not be the best long term solution to log out the help commands manually, but it would've helped as first time experience to see if the data fits your needs.
=> Add guidance to use CLI with submodules

src/lib/getCrumb.spec.ts, src/lib/getCrumb.ts, src/lib/options.ts, src/lib/setGlobalConfig.ts, src/lib/yahooFinanceFetch.ts
Makes logging customisable. Currently there's fair bit of noise like
>  Fetching crumb and cookies from https://finance.yahoo.com/quote/AAPL...
> Success. Cookie expires on Tue May 07 2024 00:13:50 GMT+1000 
etc. This PR makes it possible to either silence it, or pipe to standard logging destination.
The original behaviour with `console.log`'s is kept, meaning there's no breaking changes.
=> feat: Customisable logging

schema.json, src/modules/quote.spec.ts, src/modules/quote.ts, tests/http/quote-MSFT-fields-beta.json
Add beta to quote field option
This would be useful to get the beta when passing field options.
=> feat(quote): Add beta to quote field option

package.json, src/env-node.ts, src/env-test.ts, src/lib/fetchDevel.js, src/lib/getCrumb.ts, src/lib/yahooFinanceFetch.spec.ts, src/lib/yahooFinanceFetch.ts, yarn.lock
Closes # .
-  Removes `node-fetch` in favour of native fetch
Annoyingly my last [PR](https://github.com/gadicc/node-yahoo-finance2/pull/793) was clobbered when I synced with the upstream, so I'm going to replay my changes here. This change is pretty uncontroversial so I'll start with it. 
Some things that have changed since my previous PR was opened:
1. Gadi did a bunch of work to bump to node 18 and did some awesome work on making the tests faster 🙇 (this really helped me in writing this PR)
2. Gadi fixed the interface change I accidentally pushed in my giant Typebox PR 🙇 🙇 🙇 
3. CloudFlare [released](https://developers.cloudflare.com/workers/configuration/compatibility-dates/#nodejs-compatibility-flag) and then made their `nodejs_compat_v2` flag GA. This obviates the need for a bunch of …
=> Remove node-fetch in favour of native fetch

src/modules/search.schema.json, src/modules/search.test.ts, src/modules/search.ts, tests/fixtures/http/search-RAMXX.json
As of the time of writing, there are no issues associated with this pull request.
- Supports searching for `MONEY_MARKET` quotes.
- Generate a new `Search` schema that supports `MONEY_MARKET` type.
- Write a test of an example Money Market search (the quote that I use is `RAMXX`).
Thank you so much for developing and maintaining this module!
I noticed that when I search for something and the results contain a quote with a `quoteType` of `MONEY_MARKET`, the library will throw an error. I fixed it and ensured that it works.
Please let me know if there's something that I can do to enhance this pull request! Would be happy to get this merged so we can use it 😄
=> Support `MONEY_MARKET` in Search
